"""initial_schema

Revision ID: 2e21c54ad8a6
Revises: 
Create Date: 2026-09-15 02:39:58.955235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2e21c54ad8a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_index(op.f('ix_districts_state'), 'districts', ['state'], unique=False)
    op.create_table('occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupations_name'), 'occupations', ['name'], unique=True)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('nsqf_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_name'), 'qualifications', ['name'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_sector_id'), 'companies', ['sector_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_qualification_id'), 'courses', ['qualification_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('skill_demand_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('demand_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_demand_snapshots_district_id'), 'skill_demand_snapshots', ['district_id'], unique=False)
    op.create_index(op.f('ix_skill_demand_snapshots_period_end'), 'skill_demand_snapshots', ['period_end'], unique=False)
    op.create_index(op.f('ix_skill_demand_snapshots_period_start'), 'skill_demand_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_skill_demand_snapshots_sector_id'), 'skill_demand_snapshots', ['sector_id'], unique=False)
    op.create_index(op.f('ix_skill_demand_snapshots_skill_id'), 'skill_demand_snapshots', ['skill_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('demand_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('supply_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('gap_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_calculated_at'), 'skill_gaps', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_skill_gaps_district_id'), 'skill_gaps', ['district_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_gap_score'), 'skill_gaps', ['gap_score'], unique=False)
    op.create_index(op.f('ix_skill_gaps_priority'), 'skill_gaps', ['priority'], unique=False)
    op.create_index(op.f('ix_skill_gaps_skill_id'), 'skill_gaps', ['skill_id'], unique=False)
    op.create_table('skill_supply_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supply_count', sa.Integer(), nullable=False),
    sa.Column('supply_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_supply_snapshots_district_id'), 'skill_supply_snapshots', ['district_id'], unique=False)
    op.create_index(op.f('ix_skill_supply_snapshots_period_end'), 'skill_supply_snapshots', ['period_end'], unique=False)
    op.create_index(op.f('ix_skill_supply_snapshots_period_start'), 'skill_supply_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_skill_supply_snapshots_skill_id'), 'skill_supply_snapshots', ['skill_id'], unique=False)
    op.create_table('training_centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('centre_type', sa.String(length=120), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_centres_district_id'), 'training_centres', ['district_id'], unique=False)
    op.create_index(op.f('ix_training_centres_name'), 'training_centres', ['name'], unique=False)
    op.create_table('course_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'skill_id', name='uq_course_skill')
    )
    op.create_index(op.f('ix_course_skills_course_id'), 'course_skills', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_skills_skill_id'), 'course_skills', ['skill_id'], unique=False)
    op.create_table('employer_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('expected_hires_next_12_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_surveys_company_id'), 'employer_surveys', ['company_id'], unique=False)
    op.create_index(op.f('ix_employer_surveys_district_id'), 'employer_surveys', ['district_id'], unique=False)
    op.create_index(op.f('ix_employer_surveys_sector_id'), 'employer_surveys', ['sector_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=240), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('experience_min_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_district_id'), 'job_postings', ['district_id'], unique=False)
    op.create_index(op.f('ix_job_postings_external_id'), 'job_postings', ['external_id'], unique=True)
    op.create_index(op.f('ix_job_postings_occupation_id'), 'job_postings', ['occupation_id'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_postings_sector_id'), 'job_postings', ['sector_id'], unique=False)
    op.create_index(op.f('ix_job_postings_source'), 'job_postings', ['source'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('skill_gap_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['skill_gap_id'], ['skill_gaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_district_id'), 'recommendations', ['district_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_skill_gap_id'), 'recommendations', ['skill_gap_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_proficiency', sa.Integer(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', 'skill_id', name='uq_job_skill')
    )
    op.create_index(op.f('ix_job_skills_job_posting_id'), 'job_skills', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_skills_skill_id'), 'job_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_skills_skill_id'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_job_posting_id'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_recommendations_skill_gap_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_district_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_sector_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_occupation_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_external_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_district_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_employer_surveys_sector_id'), table_name='employer_surveys')
    op.drop_index(op.f('ix_employer_surveys_district_id'), table_name='employer_surveys')
    op.drop_index(op.f('ix_employer_surveys_company_id'), table_name='employer_surveys')
    op.drop_table('employer_surveys')
    op.drop_index(op.f('ix_course_skills_skill_id'), table_name='course_skills')
    op.drop_index(op.f('ix_course_skills_course_id'), table_name='course_skills')
    op.drop_table('course_skills')
    op.drop_index(op.f('ix_training_centres_name'), table_name='training_centres')
    op.drop_index(op.f('ix_training_centres_district_id'), table_name='training_centres')
    op.drop_table('training_centres')
    op.drop_index(op.f('ix_skill_supply_snapshots_skill_id'), table_name='skill_supply_snapshots')
    op.drop_index(op.f('ix_skill_supply_snapshots_period_start'), table_name='skill_supply_snapshots')
    op.drop_index(op.f('ix_skill_supply_snapshots_period_end'), table_name='skill_supply_snapshots')
    op.drop_index(op.f('ix_skill_supply_snapshots_district_id'), table_name='skill_supply_snapshots')
    op.drop_table('skill_supply_snapshots')
    op.drop_index(op.f('ix_skill_gaps_skill_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_priority'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_gap_score'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_district_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_calculated_at'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_skill_demand_snapshots_skill_id'), table_name='skill_demand_snapshots')
    op.drop_index(op.f('ix_skill_demand_snapshots_sector_id'), table_name='skill_demand_snapshots')
    op.drop_index(op.f('ix_skill_demand_snapshots_period_start'), table_name='skill_demand_snapshots')
    op.drop_index(op.f('ix_skill_demand_snapshots_period_end'), table_name='skill_demand_snapshots')
    op.drop_index(op.f('ix_skill_demand_snapshots_district_id'), table_name='skill_demand_snapshots')
    op.drop_table('skill_demand_snapshots')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_courses_qualification_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_companies_sector_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_qualifications_name'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_occupations_name'), table_name='occupations')
    op.drop_table('occupations')
    op.drop_index(op.f('ix_districts_state'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
