"""add user role

Revision ID: 709da6c84b53
Revises: 2e21c54ad8a6
Create Date: 2026-09-18 21:15:26.192948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709da6c84b53'
down_revision: Union[str, Sequence[str], None] = '2e21c54ad8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('phone_no', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone_no')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
